replicaCount:
  frontend: 2
  backend: 2
  mongodb: 1

images:
  frontend:
    repository: jeevanjacob11/taskflow-frontend
    tag: latest
    pullPolicy: IfNotPresent

  backend:
    repository: jeevanjacob11/taskflow-backend
    tag: latest
    pullPolicy: IfNotPresent

  mongodb:
    repository: mongo
    tag: "7"
    pullPolicy: IfNotPresent

services:
  frontend:
    type: ClusterIP
    port: 80
    targetPort: 80

  backend:
    type: ClusterIP
    port: 5000
    targetPort: 5000

  mongodb:
    port: 27017
    targetPort: 27017

resources:
  frontend:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "500m"
      memory: "256Mi"

  backend:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "500m"
      memory: "256Mi"

  mongodb:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"

mongodb:
  database: taskflow
  storage:
    size: 5Gi

ingress:
  enabled: true
  className: nginx
  host: taskflow.local
