apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-backend
spec:
  selector:
    app: {{ .Release.Name }}-backend

  ports:
    - protocol: TCP
      port: {{ .Values.services.backend.port }}
      targetPort: {{ .Values.services.backend.targetPort }}

  type: ClusterIP