apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-mongodb
  labels:
    app: {{ .Release.Name }}-mongodb

spec:
  strategy:
    type: Recreate
  replicas: {{ .Values.replicaCount.mongodb }}

  selector:
    matchLabels:
      app: {{ .Release.Name }}-mongodb

  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-mongodb

    spec:
      containers:
        - name: mongodb
          image: "{{ .Values.images.mongodb.repository }}:{{ .Values.images.mongodb.tag }}"
          imagePullPolicy: {{ .Values.images.mongodb.pullPolicy }}

          args:
            - "--auth"

          ports:
            - name: mongodb
              containerPort: 27017
              protocol: TCP

          env:
            - name: MONGO_INITDB_DATABASE
              value: "{{ .Values.mongodb.database }}"

            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-mongodb-secret
                  key: MONGO_USERNAME

            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-mongodb-secret
                  key: MONGO_PASSWORD

          resources:
            {{- toYaml .Values.resources.mongodb | nindent 12 }}

          volumeMounts:
            - name: mongodb-storage
              mountPath: /data/db

          readinessProbe:
            tcpSocket:
              port: 27017
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6

          livenessProbe:
            tcpSocket:
              port: 27017
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3

      volumes:
        - name: mongodb-storage
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-mongodb-pvc
